using Microsoft.AspNetCore.Mvc;

namespace App_03.Controllers
{
    public class TestController : Controller
    {
        public IActionResult Index()
        {
            return View("This text is generated by Test Controller: Method-Index ");
        }
        public IActionResult Index2()
        {
            return View("This text is generated by Test Controller: Method-Index ");
        }
        public IActionResult Technology() 
        {
            List<string> list = new List<string>();
            list.Add("ASP.NET core MVC");
            list.Add("C# Programming");
            list.Add("MS SQL Server Database");
            list.Add("Entity Framework Core");
            list.Add("Razor Syntax");
            list.Add("BootStrap, CSS");
            list.Add("JavaScript");
            list.Add("JQuery");

            return Json(list);

        }
        public IActionResult RegForm() 
        {
            return View();
        }
        [HttpPost]
        public IActionResult RegForm(string stdname, string stdemail, string stdmobile )
        {
            ViewBag.name = stdname;
            ViewBag.email = stdemail;
            ViewBag.mobile = stdmobile;

            if(string.IsNullOrEmpty(stdname))
            {
                ViewBag.msg = "Please enter Student Name";
                return View();
            }
            if (string.IsNullOrEmpty(stdmobile))
            {
                ViewBag.msg = "Please enter Mobile Number";
                return View();
            }
            if (string.IsNullOrEmpty(stdemail))
            {
                ViewBag.msg = "Please enter Your Mail ID";
                return View();
            }
            ViewBag.name = stdname.Trim().ToUpper();
            ViewBag.email = stdemail.Trim().ToUpper();
            ViewBag.mobile = stdmobile.Trim().ToUpper();

            return View("Submitted");
        }
    }
    
}
